<?php
/**
 * @file
 * fc_project.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function fc_project_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function fc_project_views_api() {
  return array("version" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function fc_project_node_info() {
  $items = array(
    'project' => array(
      'name' => t('Project'),
      'base' => 'node_content',
      'description' => t('Each <em>Project</em> describes a single NCLFA Project.'),
      'has_title' => '1',
      'title_label' => t('Project Name'),
      'help' => '',
    ),
  );
  return $items;
}
